image: git.m4xw.net:4567/switch/retroarch/libnx-docker-image:develop

variables:
  PACKAGE_FOLDER: "sys-clk"

stages:
  - package

nightly:
  stage: package
  image: git.m4xw.net:4567/switch/retroarch/libnx-docker-image:develop
  script:
    - bash build.sh $PACKAGE_FOLDER develop
  artifacts:
    name: $PACKAGE_FOLDER
    expire_in: 24 hours
    paths:
    - $PACKAGE_FOLDER
  except:
    - master
